# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "otus" do |otus|
    otus.vm.hostname = "otus"
    otus.vm.network "private_network", ip: "192.168.56.11"
    otus.vm.provider "virtualbox" do |virtualbox|
      virtualbox.cpus = "2"
      virtualbox.memory = "2048"
      virtualbox.name = "homework_lesson_03"
    end
  end

end 
